version: '2.1'

services:
  docker-nodejs-helloworld:
    image: vinaymavi/nodejs-helloworld-alpine
    build: .
    volumes: 
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000